### ISSUE TITLE
Unexpected parsing results

### ISSUE THREAD

**Issue by DvdGiessen** [pbrisbin/hs-shellwords#7]
I ran into some unexpected parsing results.

When including `=` (equals sign) in the input string:

```hs
ShellWords.parse "foo=123 bar" == Right ["foo=123", "bar"]
-- Fail: Instead it parses as Right ["foo"]

ShellWords.parse "foo bar=123 cow" == Right ["foo", "bar=123", "cow"]
-- Fail: Instead it parses as ["foo","bar"]
```

When escaping any reserved character by putting it within quotes:

```hs
ShellWords.parse "foo bar'();='bar cow" == Right ["foo", "bar();=bar", "cow"]
-- Fail: Instead it parses as Right ["foo","bar'"]
```

When parsing adjacent quoted strings:

```hs
ShellWords.parse "foo 'ba'\"r\" cow" == Right ["foo","bar","cow"]
-- Fail: Instead it parses as Right ["foo","ba"]
```

First, it wasn't immediately clear to me what was going wrong, since instead of returning an error the library simply returned a truncated version of the input. Perhaps we shouldn't return a `Right` when the string failed to parse correctly / completely.

As for the first case with the equals sign: I don't think an equal sign should have any special handling. The only case where the shell does so is at the start of the line (see [the specification](https://pubs.opengroup.org/onlinepubs/9799919799/utilities/V3_chap02.html#tag_19_10_02)); which doesn't seem desirable for the primary use case this library describes in its README.

(And if we want to add an environment parsing option like the Python library has, it should be fairly trivial to split the list in a separate function).

There is also a number of characters that probably *should* be marked as reserved and be required to be escaped. [Here](https://unix.stackexchange.com/a/270979) is a fairly good overview.

For reference, how I tested how the shell parses arguments by checking what various programming languages get passed to their `argv`:

```
python -c 'import sys; print(repr(sys.argv))' ...args
perl -e 'use Data::Dump qw(dump); print dump(@ARGV);' ...args
node -e 'console.log(process.argv)' ...args
php -r 'var_dump($argv);' ...args
ruby -e 'print ARGV' ...args
```

**Comment by pbrisbin** [comment]
Thanks for those test cases. I'm not immediately sure if there's a single root cause or if there are multiple issues here, but it'd be great to get these cases in the test suite and address them.

> Perhaps we shouldn't return a `Right` when the string failed to parse completely

Agreed. If there's an internal `Parser a` that I'm using, that might leave leftovers, but the top-level use of it should still be `runParser $ that >> eof` to ensure a complete parse when used there. I probably just got his bit wrong somehow.

**Comment by pbrisbin** [comment]
So removing `=`s as reserved addresses the first cases.

The other cases all stem from not even attempting to parse string-adjacency correctly. It's tangentially related to `=` being handled specially because that's the only way a case like `--foo='bar'` _is_ being parsed correctly. Unfortunately, I have to rewrite things a bit to get adjacent strings working at all, but if I did, then `=` wouldn't have to be special anyway because that example would already Just Work.
